package entidades;
// default package
// Generated 21/01/2014 08:02:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anuncios generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "anuncios", catalog = "BD_SSC")
public class Anuncios implements java.io.Serializable {

	private Integer idAnuncio;
	private String textoMensaje;
	private Date fecha;
	private String estado;
	private String membrete;
	private Set<Productos> productoses = new HashSet<Productos>(0);
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public Anuncios() {
	}

	public Anuncios(String textoMensaje, Date fecha, String estado,
			String membrete, Set<Productos> productoses,
			Set<Clientes> clienteses) {
		this.textoMensaje = textoMensaje;
		this.fecha = fecha;
		this.estado = estado;
		this.membrete = membrete;
		this.productoses = productoses;
		this.clienteses = clienteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAnuncio", unique = true, nullable = false)
	public Integer getIdAnuncio() {
		return this.idAnuncio;
	}

	public void setIdAnuncio(Integer idAnuncio) {
		this.idAnuncio = idAnuncio;
	}

	@Column(name = "textoMensaje", length = 1000)
	public String getTextoMensaje() {
		return this.textoMensaje;
	}

	public void setTextoMensaje(String textoMensaje) {
		this.textoMensaje = textoMensaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado", length = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "membrete", length = 500)
	public String getMembrete() {
		return this.membrete;
	}

	public void setMembrete(String membrete) {
		this.membrete = membrete;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anuncioses")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anuncioses")
	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
