package entidades;
// default package
// Generated 21/01/2014 08:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineaDePedidoId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class LineaDePedidoId implements java.io.Serializable {

	private int idLinea;
	private int idPedido;

	public LineaDePedidoId() {
	}

	public LineaDePedidoId(int idLinea, int idPedido) {
		this.idLinea = idLinea;
		this.idPedido = idPedido;
	}

	@Column(name = "idLinea", nullable = false)
	public int getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(int idLinea) {
		this.idLinea = idLinea;
	}

	@Column(name = "idPedido", nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineaDePedidoId))
			return false;
		LineaDePedidoId castOther = (LineaDePedidoId) other;

		return (this.getIdLinea() == castOther.getIdLinea())
				&& (this.getIdPedido() == castOther.getIdPedido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdLinea();
		result = 37 * result + this.getIdPedido();
		return result;
	}

}
