package entidades;
// default package
// Generated 23/01/2014 20:39:53 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaDePedido generated by hbm2java
 */
@Entity
@Table(name = "lineaDePedido", catalog = "BD_SSC")
public class LineaDePedido implements java.io.Serializable {

	private LineaDePedidoId id;
	private Pedidos pedidos;
	private Productos productos;
	private Integer cantidad;

	public LineaDePedido() {
	}

	public LineaDePedido(LineaDePedidoId id, Pedidos pedidos,
			Productos productos) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
	}

	public LineaDePedido(LineaDePedidoId id, Pedidos pedidos,
			Productos productos, Integer cantidad) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
		this.cantidad = cantidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idLinea", column = @Column(name = "idLinea", nullable = false)),
			@AttributeOverride(name = "idPedido", column = @Column(name = "idPedido", nullable = false)) })
	public LineaDePedidoId getId() {
		return this.id;
	}

	public void setId(LineaDePedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPedido", nullable = false, insertable = false, updatable = false)
	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProducto", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
