package entidades;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineasDeVentasId generated by hbm2java
 */
@Embeddable
public class LineasDeVentasId implements java.io.Serializable {

	private int idVenta;
	private int idProducto;

	public LineasDeVentasId() {
	}

	public LineasDeVentasId(int idVenta, int idProducto) {
		this.idVenta = idVenta;
		this.idProducto = idProducto;
	}

	@Column(name = "idVenta", nullable = false)
	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	@Column(name = "idProducto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineasDeVentasId))
			return false;
		LineasDeVentasId castOther = (LineasDeVentasId) other;

		return (this.getIdVenta() == castOther.getIdVenta())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVenta();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
