package entidades;
// default package
// Generated 21/01/2014 08:02:06 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ParametrosNegocio generated by hbm2java
 */
@Entity
@Table(name = "parametrosNegocio", catalog = "BD_SSC")
public class ParametrosNegocio implements java.io.Serializable {

	private ParametrosNegocioId id;

	public ParametrosNegocio() {
	}

	public ParametrosNegocio(ParametrosNegocioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "membrete", column = @Column(name = "membrete", length = 500)),
			@AttributeOverride(name = "ultIdPedido", column = @Column(name = "ultIdPedido")) })
	public ParametrosNegocioId getId() {
		return this.id;
	}

	public void setId(ParametrosNegocioId id) {
		this.id = id;
	}

}
