package entidades;
// default package
// Generated 21/01/2014 08:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametrosNegocioId generated by hbm2java
 */
@Embeddable
public class ParametrosNegocioId implements java.io.Serializable {

	private String membrete;
	private Integer ultIdPedido;

	public ParametrosNegocioId() {
	}

	public ParametrosNegocioId(String membrete, Integer ultIdPedido) {
		this.membrete = membrete;
		this.ultIdPedido = ultIdPedido;
	}

	@Column(name = "membrete", length = 500)
	public String getMembrete() {
		return this.membrete;
	}

	public void setMembrete(String membrete) {
		this.membrete = membrete;
	}

	@Column(name = "ultIdPedido")
	public Integer getUltIdPedido() {
		return this.ultIdPedido;
	}

	public void setUltIdPedido(Integer ultIdPedido) {
		this.ultIdPedido = ultIdPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametrosNegocioId))
			return false;
		ParametrosNegocioId castOther = (ParametrosNegocioId) other;

		return ((this.getMembrete() == castOther.getMembrete()) || (this
				.getMembrete() != null && castOther.getMembrete() != null && this
				.getMembrete().equals(castOther.getMembrete())))
				&& ((this.getUltIdPedido() == castOther.getUltIdPedido()) || (this
						.getUltIdPedido() != null
						&& castOther.getUltIdPedido() != null && this
						.getUltIdPedido().equals(castOther.getUltIdPedido())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMembrete() == null ? 0 : this.getMembrete().hashCode());
		result = 37
				* result
				+ (getUltIdPedido() == null ? 0 : this.getUltIdPedido()
						.hashCode());
		return result;
	}

}
