package entidades;
// default package
// Generated 23/01/2014 20:39:53 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PreciosId generated by hbm2java
 */
@Embeddable
public class PreciosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5016477078427138234L;
	private int idPrecio;
	private int idProducto;

	public PreciosId() {
	}

	public PreciosId(int idPrecio, int idProducto) {
		this.idPrecio = idPrecio;
		this.idProducto = idProducto;
	}

	@Column(name = "idPrecio", nullable = false)
	public int getIdPrecio() {
		return this.idPrecio;
	}

	public void setIdPrecio(int idPrecio) {
		this.idPrecio = idPrecio;
	}

	@Column(name = "idProducto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreciosId))
			return false;
		PreciosId castOther = (PreciosId) other;

		return (this.getIdPrecio() == castOther.getIdPrecio())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPrecio();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
