package entidades;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "BD_SSC", uniqueConstraints = @UniqueConstraint(columnNames = "codProducto"))
public class Productos implements java.io.Serializable {

	private Integer idProducto;
	private Subcategorias subcategorias;
	private String codProducto;
	private String nombre;
	private Integer stock;
	private Set<Anuncios> anuncioses = new HashSet<Anuncios>(0);
	private Set<Precios> precioses = new HashSet<Precios>(0);
	private Set<LineasDeVentas> lineasDeVentases = new HashSet<LineasDeVentas>(
			0);
	private Set<LineaDePedido> lineaDePedidos = new HashSet<LineaDePedido>(0);

	public Productos() {
	}

	public Productos(String codProducto) {
		this.codProducto = codProducto;
	}

	public Productos(Subcategorias subcategorias, String codProducto,
			String nombre, Integer stock, Set<Anuncios> anuncioses,
			Set<Precios> precioses, Set<LineasDeVentas> lineasDeVentases,
			Set<LineaDePedido> lineaDePedidos) {
		this.subcategorias = subcategorias;
		this.codProducto = codProducto;
		this.nombre = nombre;
		this.stock = stock;
		this.anuncioses = anuncioses;
		this.precioses = precioses;
		this.lineasDeVentases = lineasDeVentases;
		this.lineaDePedidos = lineaDePedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProducto", unique = true, nullable = false)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSubcategoria")
	public Subcategorias getSubcategorias() {
		return this.subcategorias;
	}

	public void setSubcategorias(Subcategorias subcategorias) {
		this.subcategorias = subcategorias;
	}

	@Column(name = "codProducto", unique = true, nullable = false, length = 8)
	public String getCodProducto() {
		return this.codProducto;
	}

	public void setCodProducto(String codProducto) {
		this.codProducto = codProducto;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "productos_anuncios", catalog = "BD_SSC", joinColumns = { @JoinColumn(name = "idProducto", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idAnuncio", nullable = false, updatable = false) })
	public Set<Anuncios> getAnuncioses() {
		return this.anuncioses;
	}

	public void setAnuncioses(Set<Anuncios> anuncioses) {
		this.anuncioses = anuncioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Precios> getPrecioses() {
		return this.precioses;
	}

	public void setPrecioses(Set<Precios> precioses) {
		this.precioses = precioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<LineasDeVentas> getLineasDeVentases() {
		return this.lineasDeVentases;
	}

	public void setLineasDeVentases(Set<LineasDeVentas> lineasDeVentases) {
		this.lineasDeVentases = lineasDeVentases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<LineaDePedido> getLineaDePedidos() {
		return this.lineaDePedidos;
	}

	public void setLineaDePedidos(Set<LineaDePedido> lineaDePedidos) {
		this.lineaDePedidos = lineaDePedidos;
	}
	
	
	
	
	
	
	
	
	
	
	
	

}
