package entidades;
// default package
// Generated 23/01/2014 20:39:53 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubcategoriasId generated by hbm2java
 */
@Embeddable
public class SubcategoriasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6091342518570049833L;
	private int idSubcategoria;
	private int idCategoria;

	public SubcategoriasId() {
	}

	public SubcategoriasId(int idSubcategoria, int idCategoria) {
		this.idSubcategoria = idSubcategoria;
		this.idCategoria = idCategoria;
	}

	@Column(name = "idSubcategoria", nullable = false)
	public int getIdSubcategoria() {
		return this.idSubcategoria;
	}

	public void setIdSubcategoria(int idSubcategoria) {
		this.idSubcategoria = idSubcategoria;
	}

	@Column(name = "idCategoria", nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubcategoriasId))
			return false;
		SubcategoriasId castOther = (SubcategoriasId) other;

		return (this.getIdSubcategoria() == castOther.getIdSubcategoria())
				&& (this.getIdCategoria() == castOther.getIdCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSubcategoria();
		result = 37 * result + this.getIdCategoria();
		return result;
	}

}
