package entidades;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subcategorias generated by hbm2java
 */
@Entity
@Table(name = "subcategorias", catalog = "BD_SSC")
public class Subcategorias implements java.io.Serializable {

	private int idSubcategoria;
	private Categorias categorias;
	private String descripcion;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Subcategorias() {
	}

	public Subcategorias(int idSubcategoria, Categorias categorias) {
		this.idSubcategoria = idSubcategoria;
		this.categorias = categorias;
	}

	public Subcategorias(int idSubcategoria, Categorias categorias,
			String descripcion, Set<Productos> productoses) {
		this.idSubcategoria = idSubcategoria;
		this.categorias = categorias;
		this.descripcion = descripcion;
		this.productoses = productoses;
	}

	@Id
	@Column(name = "idSubcategoria", unique = true, nullable = false)
	public int getIdSubcategoria() {
		return this.idSubcategoria;
	}

	public void setIdSubcategoria(int idSubcategoria) {
		this.idSubcategoria = idSubcategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoria", nullable = false)
	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategorias")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
