package entidades;
// default package
// Generated 21/01/2014 08:02:06 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subcategorias generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "subcategorias", catalog = "BD_SSC")
public class Subcategorias implements java.io.Serializable {

	private Integer idSubcategoria;
	private Categorias categorias;
	private String descripcion;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Subcategorias() {
	}

	public Subcategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public Subcategorias(Categorias categorias, String descripcion,
			Set<Productos> productoses) {
		this.categorias = categorias;
		this.descripcion = descripcion;
		this.productoses = productoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSubcategoria", unique = true, nullable = false)
	public Integer getIdSubcategoria() {
		return this.idSubcategoria;
	}

	public void setIdSubcategoria(Integer idSubcategoria) {
		this.idSubcategoria = idSubcategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoria", nullable = false)
	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategorias")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
