// default package
// Generated 09/02/2015 13:06:36 by Hibernate Tools 3.4.0.CR1
package entidades;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userdetail generated by hbm2java
 */
@Entity
@Table(name = "userdetail", catalog = "BD_SSC")
public class Userdetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5020822505644084224L;
	private int id;
	private String name;
	private String username;
	private String password;

	public Userdetail() {
	}

	public Userdetail(int id) {
		this.id = id;
	}

	public Userdetail(int id, String name, String username, String password) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username", length = 35)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 35)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
