package main.java;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ParametrosNegocio generated by hbm2java
 */
@Entity
@Table(name = "parametrosNegocio", catalog = "BD_SSC")
public class ParametrosNegocio implements java.io.Serializable {

	private ParametrosNegocioId id;

	public ParametrosNegocio() {
	}

	public ParametrosNegocio(ParametrosNegocioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "membrete", column = @Column(name = "membrete", nullable = false, length = 500)),
			@AttributeOverride(name = "ultIdPedido", column = @Column(name = "ultIdPedido", nullable = false)) })
	public ParametrosNegocioId getId() {
		return this.id;
	}

	public void setId(ParametrosNegocioId id) {
		this.id = id;
	}

}
