package main.java;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Precios generated by hbm2java
 */
@Entity
@Table(name = "precios", catalog = "BD_SSC")
public class Precios implements java.io.Serializable {

	private Integer idPrecio;
	private Productos productos;
	private Date fechaDesde;
	private Date fechaHasta;
	private Float precio;
	private Float precioPromocional;

	public Precios() {
	}

	public Precios(Productos productos, Date fechaDesde, Date fechaHasta,
			Float precio, Float precioPromocional) {
		this.productos = productos;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.precio = precio;
		this.precioPromocional = precioPromocional;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPrecio", unique = true, nullable = false)
	public Integer getIdPrecio() {
		return this.idPrecio;
	}

	public void setIdPrecio(Integer idPrecio) {
		this.idPrecio = idPrecio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProducto")
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaDesde", length = 19)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaHasta", length = 19)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "precio", precision = 8)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@Column(name = "precioPromocional", precision = 15, scale = 3)
	public Float getPrecioPromocional() {
		return this.precioPromocional;
	}

	public void setPrecioPromocional(Float precioPromocional) {
		this.precioPromocional = precioPromocional;
	}

}
