package datos;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anuncios generated by hbm2java
 */
@Entity
@Table(name = "anuncios", catalog = "BD_SSC")
public class Anuncios implements java.io.Serializable {

	private int idAnuncio;
	private String textoMensaje;
	private Date fecha;
	private String estado;
	private Set<Productos> productoses = new HashSet<Productos>(0);
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public Anuncios() {
	}

	public Anuncios(int idAnuncio) {
		this.idAnuncio = idAnuncio;
	}

	public Anuncios(int idAnuncio, String textoMensaje, Date fecha,
			String estado, Set<Productos> productoses, Set<Clientes> clienteses) {
		this.idAnuncio = idAnuncio;
		this.textoMensaje = textoMensaje;
		this.fecha = fecha;
		this.estado = estado;
		this.productoses = productoses;
		this.clienteses = clienteses;
	}

	@Id
	@Column(name = "idAnuncio", unique = true, nullable = false)
	public int getIdAnuncio() {
		return this.idAnuncio;
	}

	public void setIdAnuncio(int idAnuncio) {
		this.idAnuncio = idAnuncio;
	}

	@Column(name = "textoMensaje", length = 1000)
	public String getTextoMensaje() {
		return this.textoMensaje;
	}

	public void setTextoMensaje(String textoMensaje) {
		this.textoMensaje = textoMensaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado", length = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anuncioses")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anuncioses")
	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
