package datos;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaDePedido generated by hbm2java
 */
@Entity
@Table(name = "lineaDePedido", catalog = "BD_SSC")
public class LineaDePedido implements java.io.Serializable {

	private Integer idLinea;
	private Pedidos pedidos;
	private Productos productos;
	private Integer cantidad;

	public LineaDePedido() {
	}

	public LineaDePedido(Pedidos pedidos, Productos productos) {
		this.pedidos = pedidos;
		this.productos = productos;
	}

	public LineaDePedido(Pedidos pedidos, Productos productos, Integer cantidad) {
		this.pedidos = pedidos;
		this.productos = productos;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLinea", unique = true, nullable = false)
	public Integer getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(Integer idLinea) {
		this.idLinea = idLinea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPedido", nullable = false)
	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProducto", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
