package datos;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineasDeVentas generated by hbm2java
 */
@Entity
@Table(name = "lineasDeVentas", catalog = "BD_SSC")
public class LineasDeVentas implements java.io.Serializable {

	private LineasDeVentasId id;
	private Ventas ventas;
	private Productos productos;
	private Float subtotal;
	private Integer cantidad;

	public LineasDeVentas() {
	}

	public LineasDeVentas(LineasDeVentasId id, Ventas ventas,
			Productos productos) {
		this.id = id;
		this.ventas = ventas;
		this.productos = productos;
	}

	public LineasDeVentas(LineasDeVentasId id, Ventas ventas,
			Productos productos, Float subtotal, Integer cantidad) {
		this.id = id;
		this.ventas = ventas;
		this.productos = productos;
		this.subtotal = subtotal;
		this.cantidad = cantidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idVenta", column = @Column(name = "idVenta", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "idProducto", nullable = false)) })
	public LineasDeVentasId getId() {
		return this.id;
	}

	public void setId(LineasDeVentasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVenta", nullable = false, insertable = false, updatable = false)
	public Ventas getVentas() {
		return this.ventas;
	}

	public void setVentas(Ventas ventas) {
		this.ventas = ventas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProducto", nullable = false, insertable = false, updatable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "subtotal", precision = 11, scale = 0)
	public Float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
