package datos;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametrosNegocioId generated by hbm2java
 */
@Embeddable
public class ParametrosNegocioId implements java.io.Serializable {

	private String membrete;
	private int ultIdPedido;

	public ParametrosNegocioId() {
	}

	public ParametrosNegocioId(String membrete, int ultIdPedido) {
		this.membrete = membrete;
		this.ultIdPedido = ultIdPedido;
	}

	@Column(name = "membrete", nullable = false, length = 500)
	public String getMembrete() {
		return this.membrete;
	}

	public void setMembrete(String membrete) {
		this.membrete = membrete;
	}

	@Column(name = "ultIdPedido", nullable = false)
	public int getUltIdPedido() {
		return this.ultIdPedido;
	}

	public void setUltIdPedido(int ultIdPedido) {
		this.ultIdPedido = ultIdPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametrosNegocioId))
			return false;
		ParametrosNegocioId castOther = (ParametrosNegocioId) other;

		return ((this.getMembrete() == castOther.getMembrete()) || (this
				.getMembrete() != null && castOther.getMembrete() != null && this
				.getMembrete().equals(castOther.getMembrete())))
				&& (this.getUltIdPedido() == castOther.getUltIdPedido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMembrete() == null ? 0 : this.getMembrete().hashCode());
		result = 37 * result + this.getUltIdPedido();
		return result;
	}

}
