package datos;

// Generated 27/06/2013 20:12:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ventas generated by hbm2java
 */
@Entity
@Table(name = "ventas", catalog = "BD_SSC")
public class Ventas implements java.io.Serializable {

	private Integer idVenta;
	private Clientes clientes;
	private Date fecha;
	private Float total;
	private Set<LineasDeVentas> lineasDeVentases = new HashSet<LineasDeVentas>(
			0);

	public Ventas() {
	}

	public Ventas(Clientes clientes, Date fecha, Float total,
			Set<LineasDeVentas> lineasDeVentases) {
		this.clientes = clientes;
		this.fecha = fecha;
		this.total = total;
		this.lineasDeVentases = lineasDeVentases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVenta", unique = true, nullable = false)
	public Integer getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(Integer idVenta) {
		this.idVenta = idVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente")
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "total", precision = 9, scale = 3)
	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ventas")
	public Set<LineasDeVentas> getLineasDeVentases() {
		return this.lineasDeVentases;
	}

	public void setLineasDeVentases(Set<LineasDeVentas> lineasDeVentases) {
		this.lineasDeVentases = lineasDeVentases;
	}

}
